
update avocado_dataconcept set name='MRS Results' where id=191;
update avocado_dataconcept set name='Nerve Biopsy' where id=194;
update avocado_dataconcept set name='Nerve Biopsy Results' where id=195;
update avocado_dataconcept set name='CT-Age' where id=183;
update avocado_dataconcept set name='MRI-Brain' where id=152;
update avocado_dataconcept set name='CT' where id=181;
update avocado_dataconcept set name='MRS' where id=190;
update avocado_dataconcept set name='MRI-Brain-Age' where id=154;
update avocado_dataconcept set name='MRI-Spine' where id=156;
update avocado_dataconcept set name='MRI-Spine Results' where id=157;
update avocado_dataconcept set name='Spinal Tap' where id=160;
update avocado_dataconcept set name='Spinal Tap Results' where id=161;
update avocado_dataconcept set name='Spinal Tap-Age' where id=162;
update avocado_dataconcept set name='Spinal Tap-Protein' where id=163;
update avocado_dataconcept set name='BAER' where id=165;
update avocado_dataconcept set name='BAER Results' where id=166;
update avocado_dataconcept set name='BAER-Age' where id=167;
update avocado_dataconcept set name='VER' where id=169;
update avocado_dataconcept set name='VER Results' where id=170;
update avocado_dataconcept set name='VER-Age' where id=171;
update avocado_dataconcept set name='Nerve Conduction' where id=173;
update avocado_dataconcept set name='Nere Conduction Results' where id=174;
update avocado_dataconcept set name='Nerve Conduction-Age' where id=175;
update avocado_dataconcept set name='EEG' where id=177;
update avocado_dataconcept set name='EEG Results' where id=178;
update avocado_dataconcept set name='EEG-Age' where id=179;
update avocado_dataconcept set name='MRI-Brain Results' where id=153;
update avocado_dataconcept set name='CT Results' where id=182;
update avocado_dataconcept set name='Muscle Biopsy Results' where id=186;
